import type { FastifyPluginAsync } from 'fastify';
import { healthRoutes } from './health.js';
import { mediaRoutes } from './media.js';
import { agentRoutes } from './agent.js';
import { emailRoutes } from './email.js';
import { feedRoutes } from './feed.js';
import { profileRoutes } from './profile.js';
import { userRoutes } from '../modules/users/user.route.js';
import { eventRoutes } from '../modules/events/event.route.js';
import { recommendationRoutes } from '../modules/recommendations/recommendation.route.js';
import { commentRoutes } from '../modules/comments/comment.route.js';
import { likeRoutes } from '../modules/likes/like.route.js';
import { proposalRoutes } from '../modules/proposals/proposal.route.js';
import { movieRoutes } from '../modules/movies/movie.route.js';
import { postcardRoutes } from '../modules/postcards/postcard.route.js';
import { aboutRoutes } from '../modules/about/about.route.js';

export const apiRoutes: FastifyPluginAsync = async (app) => {
  app.register(healthRoutes, { prefix: '/health' });
  app.register(userRoutes, { prefix: '/users' });
  app.register(eventRoutes, { prefix: '/events' });
  app.register(recommendationRoutes, { prefix: '/recommendations' });
  app.register(commentRoutes, { prefix: '/comments' });
  app.register(likeRoutes, { prefix: '/likes' });
  app.register(proposalRoutes, { prefix: '/proposals' });
  app.register(movieRoutes, { prefix: '/movies' });
  app.register(postcardRoutes, { prefix: '/postcards' });
  app.register(aboutRoutes, { prefix: '/about' });
  app.register(feedRoutes, { prefix: '/feed' });
  app.register(profileRoutes, { prefix: '/profile' });
  app.register(mediaRoutes, { prefix: '/media' });
  app.register(emailRoutes, { prefix: '/email' });
  app.register(agentRoutes, { prefix: '/agent' });
};
