-- Add address fields to User
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "city" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "state" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "zipCode" TEXT NOT NULL DEFAULT '';

-- Add address fields to Event
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "city" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "state" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "zipCode" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "address" TEXT NOT NULL DEFAULT '';
